version: '3.3'

services:
  docstampr-api-rest-dev:
    image: civisblockchain/docstampr-api-rest:0.2.0
    environment:
      - ssm_name=docstampr-loop-beta
      - ssm_coop_url=http://peer0.pr-bc1.civis-blockchain.org:9090
      - ssm_signer_admin_name=adrien
      - ssm_signer_admin_key=file:/opt/docstampr/user/adrien
      - ssm_signer_user_name=docstampr
      - ssm_signer_user_key=file:/opt/docstampr/user/docstampr
      - docstampr_git_repo=file:/opt/docstampr/git
      - docstampr_git_key=file:/opt/docstampr/user/id_rsa.civis.github
      - docstampr_git_push=true
      - docstampr_aes_key=
    volumes:
      - ./infra/bc1/user:/opt/docstampr/user
      - ./infra/civis-docstampr-file:/opt/docstampr/git
    ports:
      - 8889:8889