version: '3.3'

services:
  docstampr-api-rest:
    image: civisblockchain/docstampr-api-rest
    environment:
      - coop_rest_url=http://peer0.pr-bc1.civis-blockchain.org:9090
      - ssm_name=docstampr
      - signer_admin_name=adrien
      - signer_admin_file=file:/opt/docstampr/user/adrien
      - signer_user_name=docstampr
      - signer_user_file=file:/opt/docstampr/user/docstampr
    volumes:
      - ./infra/bc1/user:/opt/docstampr/user
    ports:
      - 8888:8888