version: '3.3'

services:
  docstampr-api-rest:
    image: civisblockchain/docstampr-api-rest:0.1.0
    environment:
      - ssm_name=docstampr-beta
      - ssm_coop_rest_url=http://peer0.pr-bc1.civis-blockchain.org:9090
      - ssm_signer_admin_name=adrien
      - ssm_signer_admin_file=file:/opt/docstampr/user/adrien
      - ssm_signer_user_name=docstampr
      - ssm_signer_user_file=file:/opt/docstampr/user/docstampr
      - docstampr_git_repo=file:/opt/docstampr/git
      - docstampr_git_key=file:/opt/docstampr/user/id_rsa.civis.github
      - docstampr_git_push=true
    volumes:
      - ./infra/bc1/user:/opt/docstampr/user
      - ./infra/bc1/civis-docstampr-file:/opt/docstampr/git
    ports:
      - 8889:8889