ssm:
  name: docstampr
  coop:
    rest:
      url: http://localhost:9090
  signer:
    admin:
      name: adam
      file: file:./infra/network-it/util/adam
    user:
      name: bob
      file: file:./infra/network-it/util/bob

docstampr:
  git:
    repo: file:./infra/docstampr-file

server:
  port : 8888