ssm:
  name: docstampr-loop
  coop:
    url: http://localhost:9090
  signer:
    admin:
      name: adam
      key: file:./infra/dev/user/adam
    user:
      name: bob
      key: file:./infra/dev/user/bob

docstampr:
  git:
    repo: file:./infra/dev/git/docstampr-file
    key: file:./infra/bc1/id_rsa.civis.github
    push: false

server:
  port: 8889